config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'bookings#new'

  resources :bookings, only: %i[index new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

# Purpose: To create a booking model for the database
class Booking < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :animal_name, presence: true
  validates :animal_type, presence: true
  validates :hours_requested, presence: true
  validates :date_of_service, presence: true
  validates :hours_requested,
            numericality: { only_integer: true, greater_than_or_equal_to: 2, less_than_or_equal_to: 8 }
  validates :animal_type, inclusion: { in: %w[dog cat] }
  validate :date_of_service_cannot_be_in_the_past

  def cost_of_service
    cost = 20.0
    cost += if animal_type == 'dog'
              10.0 * hours_requested
            else
              5.0 * hours_requested
            end

    cost
  end

  private

  def date_of_service_cannot_be_in_the_past
    return unless date_of_service.present? && date_of_service < Time.zone.now

    errors.add(:date_of_service, "can't be in the past")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

# Purpose: To create a bookings controller
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      flash[:success] = 'Booking created successfully'
      redirect_to bookings_url
    else
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:first_name, :last_name, :animal_name, :animal_type, :hours_requested,
                                    :date_of_service)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= render 'shared/errors', obj: @booking %>

<div class='row'>
  <div class='col-12'>
    <%= form_for(@booking, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :first_name, "Owner's first name" %>
        </div>
        <div class='col-10'>
          <%= f.text_field :first_name %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :last_name, "Owner's last name" %>
        </div>
        <div class='col-10'>
          <%= f.text_field :last_name %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :animal_name, "Pet's name" %>
        </div>
        <div class='col-10'>
          <%= f.text_field :animal_name %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :animal_type, "Pet type" %>
        </div>
        <div class='col-10'>
          <%= f.select :animal_type, [['cat', 'cat'], ['dog', 'dog']]  %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :hours_requested, 'Hours for booking' %>
        </div>
        <div class='col-10'>
          <%= f.select :hours_requested, [['2 hrs', 2], ['3 hrs', 3], ['4 hrs', 4], ['5 hrs', 5], ['6 hrs', 6], ['7 hrs', 7], ['8 hrs', 8]] %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='control-label col-2'>
          <%= f.label :date_of_service, 'Date of service' %>
        </div>
        <div class='col-10'>
          <%= f.datetime_select(:date_of_service, ampm: true) %>
        </div>
      </div>
      <div class='form-group mb-3'>
        <div class='col-10'>
          <%= f.submit 'Book', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>All Bookings</h1>

<% @bookings.sort_by(&:date_of_service).each do |booking| %>
  <div class="card mb-3" style="width: 18rem;">
    <div class="card-header">
      <%= "#{booking.date_of_service.strftime('%B %d, %Y at %I:%M %p')}" %>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= "Owner: #{booking.first_name} #{booking.last_name}" %></li>
      <li class="list-group-item"><%= "Name of pet: #{booking.animal_name}" %></li>
      <li class="list-group-item"><%= "Type of pet: #{booking.animal_type}" %></li>
      <li class="list-group-item"><%= "Length of appointment: #{booking.hours_requested} hours" %></li>
      <li class="list-group-item"><%= "Cost of service = #{number_to_currency(booking.cost_of_service)}" %></li>
    </ul>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div>
  <div>
    <h1>Schedule Pet Sitting</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/layouts/_messages.html.erb
<div class='row'>
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary bg-opacity-75">
  <div class="container-fluid">
    <div class='navbar-hearder'>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "LoadUp's Cat and Dog Sitting Service", root_path, class: 'navbar-brand text-white', id: 'logo' %>
    </div>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav navbar-nav">
        <li class='nav-item'>
          <%= link_to 'Schedule', new_booking_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'All bookings', bookings_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetSitting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger bg-danger">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h3>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>